diccionario = {
    "amor": "Sentimiento intenso de afecto\nhacia una persona o cosa.",
    "libertad": "Derecho o facultad de actuar según\nla propia voluntad, respetando la ley\ny los derechos de los demás.",
    "felicidad": "Estado de satisfacción plena,\nalegría y bienestar.",
    "paz": "Ausencia de violencia, conflicto\no perturbación; tranquilidad.",
    "justicia": "Conjunto de principios y normas\nque regulan las relaciones humanas\nen una sociedad.",
    "esperanza": "Actitud de confianza en el futuro\ny en la posibilidad de que algo\nbueno ocurra.",
    "verdad": "Conformidad de las cosas con\nel pensamiento o la realidad.",
    "sabiduría": "Capacidad para discernir y juzgar\ncorrectamente lo que es verdadero\no falso, correcto o incorrecto.",
    "amistad": "Relación afectiva entre personas\nbasada en la confianza, el cariño\ny el apoyo mutuo.",
    "valentía": "Cualidad de enfrentarse con decisión\na situaciones difíciles o peligrosas.",
    "humildad": "Virtud que consiste en reconocer\nlas propias limitaciones y debilidades.",
    "respeto": "Consideración hacia los derechos,\nopiniones o sentimientos de los demás.",
    "compasión": "Sentimiento de pena y ternura\nhacia el sufrimiento ajeno.",
    "tolerancia": "Capacidad para aceptar ideas,\ncreencias o prácticas diferentes\na las propias.",
    "honestidad": "Cualidad de ser sincero y honrado\nen los actos y las palabras.",
    "paciencia": "Capacidad para soportar contratiempos\no retrasos sin irritarse.",
    "perseverancia": "Constancia en el esfuerzo para\nalcanzar un objetivo a pesar\nde las dificultades.",
    "generosidad": "Disposición a dar o compartir\ncon los demás sin esperar nada a cambio.",
    "lealtad": "Fidelidad a los compromisos adquiridos\no a las personas con quienes\nse tiene vínculos.",
    "equilibrio": "Estado de estabilidad o armonía\nentre diferentes elementos o fuerzas.",
    "creatividad": "Capacidad para generar ideas originales\no soluciones innovadoras.",
    "responsabilidad": "Obligación de responder por las acciones\npropias y sus consecuencias.",
    "solidaridad": "Unión o apoyo mutuo entre personas\no grupos con intereses comunes.",
    "empatía": "Capacidad para ponerse en el lugar\nde otra persona y comprender\nsus emociones.",
    "autonomía": "Capacidad de una persona para tomar\ndecisiones por sí misma.",
    "integridad": "Cualidad de ser honesto y tener fuertes\nprincipios morales.",
    "curiosidad": "Deseo de conocer o aprender cosas nuevas.",
    "disciplina": "Cumplimiento riguroso de las normas\ny deberes establecidos.",
    "optimismo": "Tendencia a ver el lado positivo\nde las cosas o a esperar resultados\nfavorables.",
    "pesimismo": "Tendencia a ver el lado negativo\nde las cosas o a esperar resultados\ndesfavorables.",
    "ambición": "Fuerte deseo de alcanzar metas importantes\no lograr éxito.",
    "orgullo": "Satisfacción personal por las propias\ncualidades o logros.",
    "modestia": "Cualidad de no presumir de las propias\nvirtudes o logros.",
    "confianza": "Seguridad en sí mismo, en los demás\no en una situación determinada.",
    "ansiedad": "Estado de inquietud o preocupación\nexcesiva por algo incierto.",
    "estrés": "Respuesta física o emocional a situaciones\nexigentes o estresantes.",
    "alegría": "Sentimiento de satisfacción o felicidad\nintensa.",
    "tristeza": "Sentimiento de pena o desconsuelo.",
    "ira": "Emoción intensa de enfado o furia.",
    "miedo": "Respuesta emocional ante una amenaza\nreal o percibida.",
    "coraje": "Valor para enfrentar situaciones\ndifíciles o peligrosas.",
    "ternura": "Cariño o afecto delicado y suave.",
    "inspiración": "Estímulo que despierta ideas creativas\no motivación.",
    "motivación": "Impulso interno que mueve a una persona\na realizar acciones.",
    "progreso": "Avance o mejora en algún aspecto\no situación.",
    "innovación": "Introducción de algo nuevo o diferente\nen un proceso o producto.",
    "tradición": "Costumbre o práctica transmitida\nde generación en generación.",
    "cultura": "Conjunto de valores, creencias,\ncostumbres y arte de una sociedad.",
    "educación": "Proceso de enseñanza y aprendizaje\npara desarrollar habilidades\ny conocimientos.",
    "conocimiento": "Información o comprensión adquirida\na través del estudio o la experiencia.",
    "experiencia": "Conjunto de vivencias o aprendizajes\nobtenidos a lo largo de la vida.",
    "habilidad": "Capacidad para realizar una tarea\no actividad con destreza.",
    "destreza": "Habilidad para ejecutar algo con\nprecisión y eficacia.",
    "talento": "Capacidad natural para destacar\nen una actividad específica.",
    "liderazgo": "Capacidad para guiar, dirigir o influir\nen un grupo de personas.",
    "colaboración": "Trabajo conjunto entre personas o grupos\npara alcanzar un objetivo común.",
    "comunicación": "Intercambio de información, ideas\no sentimientos entre personas.",
    "negociación": "Proceso de diálogo para llegar\na acuerdos beneficiosos para ambas partes.",
    "resiliencia": "Capacidad para recuperarse frente\na adversidades o traumas.",
    "adaptabilidad": "Facilidad para ajustarse a nuevas\ncircunstancias o entornos.",
    "flexibilidad": "Capacidad para cambiar o ajustarse\nsegún las necesidades.",
    "eficiencia": "Capacidad para lograr objetivos con\nel menor uso de recursos.",
    "productividad": "Medida de la cantidad de trabajo realizado\nen un tiempo determinado.",
    "calidad": "Grado de excelencia o superioridad\nde algo.",
    "excelencia": "Alto nivel de calidad o perfección\nen algo.",
    "ética": "Conjunto de principios morales que guían\nel comportamiento humano.",
    "moral": "Conjunto de valores y creencias que definen\nlo correcto o incorrecto.",
    "derecho": "Norma jurídica que regula las relaciones\nsociales y garantiza libertades.",
    "ley": "Regla o norma establecida por una\nautoridad para regular conductas.",
    "justificación": "Razón o argumento que explica o defiende\nuna acción.",
    "razonamiento": "Proceso mental para analizar información\ny llegar a conclusiones.",
    "lógica": "Ciencia que estudia los principios\ndel razonamiento correcto.",
    "argumento": "Razón o conjunto de razones utilizadas\npara defender una idea.",
    "prueba": "Evidencia o demostración que verifica\nla verdad de algo.",
    "teoría": "Explicación sistemática sobre un fenómeno\no conjunto de hechos.",
    "hipótesis": "Suposición provisional que se formula\npara ser verificada.",
    "experimento": "Procedimiento controlado para probar\nuna hipótesis.",
    "observación": "Acción de examinar detenidamente\nun fenómeno o situación.",
    "análisis": "Estudio detallado de algo para comprender\nsu naturaleza.",
    "síntesis": "Proceso de combinar elementos para formar\nun todo coherente.",
    "evaluación": "Proceso de valorar o juzgar la calidad\no importancia de algo.",
    "diagnóstico": "Identificación de una situación\no problema mediante su análisis.",
    "solución": "Respuesta o método para resolver\nun problema o dificultad.",
    "problema": "Situación complicada o difícil\nque requiere una solución.",
    "desafío": "Dificultad o tarea que requiere esfuerzo\npara superarse.",
    "oportunidad": "Momento favorable para aprovechar\nuna ventaja o beneficio.",
    "riesgo": "Posibilidad de que ocurra algo negativo\no perjudicial.",
    "seguridad": "Estado de protección contra peligros\no amenazas.",
    "incertidumbre": "Falta de certeza o claridad sobre algo.",
    "certeza": "Conocimiento claro y seguro sobre algo.",
    "duda": "Incertidumbre o falta de convicción\nsobre algo.",
    "perro": "Mamífero doméstico de la familia\nde los cánidos, comúnmente considerado\nel mejor amigo del hombre.",
    "gato": "Mamífero felino doméstico, conocido\npor su agilidad, independencia\ny comportamiento curioso.",
    "lagarto": "Reptil escamoso que habita en diversas\nregiones del mundo, caracterizado\npor su cuerpo alargado y patas cortas.",
    "verde": "Color asociado con la naturaleza,\nlos árboles y las plantas;\ntambién simboliza esperanza o juventud.",
    "rojo": "Color vibrante asociado con el fuego,\nel amor, la pasión y, en ocasiones,\nel peligro.",
    "azul": "Color asociado con el cielo, el mar\ny la calma; también simboliza\nla tristeza en algunas culturas.",
    "animal": "Ser vivo que se caracteriza por su\ncapacidad de movimiento y sensación.",
    "mascota": "Animal doméstico que vive con los humanos\ncomo compañero o para diversión.",
    "naturaleza": "Conjunto de elementos físicos y biológicos\nque conforman el mundo natural.",
    "color": "Propiedad de los objetos que depende\nde la luz que reflejan o emiten,\nperceptible por el ojo humano."
}
    
def initialize():
    while True:
        input_word = input("\nPalabra: ").lower()
        if input_word in diccionario.keys():
            print(diccionario[input_word])
        else:
            print("Esa palabra no existe dentro del diccionario.\nIngresa otra palabra")
            break
    return

while True:
    initialize()
